# Generated by Django 4.2 on 2023-05-04 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Sneakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.CharField(max_length=512, verbose_name='Description')),
                ('price', models.PositiveIntegerField(default=10, verbose_name='Price in $')),
                ('width', models.PositiveIntegerField(verbose_name='Width in mm')),
                ('height', models.PositiveIntegerField(verbose_name='Height in mm')),
                ('depth', models.PositiveIntegerField(verbose_name='Depth in mm')),
                ('weight', models.PositiveIntegerField(verbose_name='Weight in gm')),
                ('freshness_duration', models.PositiveIntegerField(verbose_name='Freshness Duration in days')),
                ('is_avalible', models.BooleanField(default=False, verbose_name='Is avalibe')),
                ('color', models.CharField(choices=[('gold', 'Gold'), ('black', 'Black'), ('spacegrey', 'Spacegrey'), ('red', 'Red'), ('blue', 'Blue')], max_length=32, verbose_name='Color of sneaker')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sneakers', to='shop.brends')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sneakers', to='shop.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('rating', models.PositiveIntegerField(default=1)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='reviews')),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.sneakers')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sneakers', to='shop.sneakers')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
