# Generated by Django 4.2 on 2023-05-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='image',
            field=models.ImageField(default=None, upload_to='media/sneakers'),
        ),
    ]
